[package]
name = "hello-label"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
rustnative-core.workspace = true
serde_json = "1"

[build-dependencies]
rustnative-build.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rustnative-linux.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
rustnative-android.workspace = true

[target.'cfg(not(any(target_os = "linux", target_os = "android")))'.dependencies]
rustnative-windows.workspace = true
