//! The pacman package format: what Arch Linux and its derivatives (Manjaro,
//! EndeavourOS) install with `pacman -U app.pkg.tar`.
//!
//! A package is a tar archive of the installed files under `usr/`, with
//! two metadata files at its root, first in the archive:
//!
//! - **`.PKGINFO`** — `key = value` lines: the name, `version-release`, the
//!   installed size, the architecture, and the dependencies `pacman`
//!   resolves before it installs;
//! - **`.MTREE`** — every entry's type, mode, size, and SHA-256 in
//!   libarchive's mtree format, gzip'd, which `pacman -Qkk` checks an
//!   installed package against.
//!
//! `makepkg` would compress the tar with zstd; `pacman` reads the archive
//! through libarchive, which accepts an uncompressed one, so the package is
//! stored as the `.deb` is — reproducible with no compressor's output to
//! depend on.

use std::fmt::Write as _;

use super::File;

/// What the package says about itself.
#[derive(Debug, Clone)]
pub struct Metadata<'a> {
    /// The package name (`[a-z0-9@._+-]`).
    pub name: &'a str,
    /// The version (`major.minor.patch`).
    pub version: &'a str,
    /// The release of this version, `1` for the first package of it.
    pub release: &'a str,
    /// One line about it.
    pub description: &'a str,
    /// Who packaged it.
    pub packager: &'a str,
    /// The architecture (`x86_64`, `aarch64`).
    pub arch: &'a str,
    /// What it depends on: a name, and optionally `>=` that version.
    pub depends: &'a [(&'a str, Option<&'a str>)],
}

/// The `.PKGINFO` file.
#[must_use]
pub fn pkginfo(metadata: &Metadata<'_>, installed_bytes: u64, time: u64) -> String {
    let mut info = format!(
        "# Generated by rustnative\npkgname = {name}\npkgbase = {name}\nxdata = pkgtype=pkg\npkgver = {}-{}\npkgdesc = {}\nbuilddate = {time}\npackager = {}\nsize = {installed_bytes}\narch = {}\nlicense = custom\n",
        metadata.version,
        metadata.release,
        metadata.description,
        metadata.packager,
        metadata.arch,
        name = metadata.name,
    );
    for (name, version) in metadata.depends {
        match version {
            Some(version) => {
                let _ = writeln!(info, "depend = {name}>={version}");
            }
            None => {
                let _ = writeln!(info, "depend = {name}");
            }
        }
    }
    info
}

/// The `.MTREE` file, before it is gzip'd: every directory and file the
/// archive holds, `.PKGINFO` included, sorted as the archive is.
#[must_use]
pub fn mtree(files: &[File], time: u64) -> String {
    let mut directories = std::collections::BTreeSet::new();
    for file in files {
        let mut path = String::new();
        let parts = file.path.split('/').collect::<Vec<_>>();
        for part in &parts[..parts.len().saturating_sub(1)] {
            if !path.is_empty() {
                path.push('/');
            }
            path.push_str(part);
            directories.insert(path.clone());
        }
    }
    let mut lines = Vec::new();
    for directory in directories {
        lines.push((directory.clone(), format!("./{directory} time={time}.0 mode=755 type=dir")));
    }
    for file in files {
        let mode = if file.executable { " mode=755" } else { "" };
        lines.push((
            file.path.clone(),
            format!(
                "./{} time={time}.0{mode} size={} sha256digest={}",
                file.path,
                file.data.len(),
                crate::package::zip::hash_of(&file.data)
            ),
        ));
    }
    lines.sort();
    let mut out = "#mtree\n/set type=file uid=0 gid=0 mode=644\n".to_owned();
    for (_, line) in lines {
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// A pacman package of `files`, whose paths are absolute paths without the
/// leading `/` (`usr/bin/app`).
#[must_use]
pub fn package(metadata: &Metadata<'_>, files: &[File], time: u64) -> Vec<u8> {
    let installed: u64 = files.iter().map(|file| file.data.len() as u64).sum();
    let info = File {
        path: ".PKGINFO".to_owned(),
        data: pkginfo(metadata, installed, time).into_bytes(),
        executable: false,
    };
    let mut described = files.to_vec();
    described.push(info.clone());
    let mut entries = files.to_vec();
    entries.push(info);
    entries.push(File {
        path: ".MTREE".to_owned(),
        data: super::gzip_stored(mtree(&described, time).as_bytes()),
        executable: false,
    });
    super::tar(&entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn metadata() -> Metadata<'static> {
        Metadata {
            name: "notes",
            version: "1.2.3",
            release: "1",
            description: "Take notes",
            packager: "Example <example@example.com>",
            arch: "x86_64",
            depends: &[("gtk4", Some("4.14")), ("libsoup3", None)],
        }
    }

    fn files() -> Vec<File> {
        vec![
            File { path: "usr/bin/notes".to_owned(), data: b"\x7fELF".to_vec(), executable: true },
            File {
                path: "usr/share/applications/com.example.Notes.desktop".to_owned(),
                data: b"[Desktop Entry]\n".to_vec(),
                executable: false,
            },
        ]
    }

    #[test]
    fn pkginfo_names_the_version_release_and_dependencies() {
        let info = pkginfo(&metadata(), 20, 0);
        for line in [
            "pkgname = notes",
            "pkgver = 1.2.3-1",
            "arch = x86_64",
            "size = 20",
            "depend = gtk4>=4.14",
            "depend = libsoup3",
        ] {
            assert!(info.lines().any(|candidate| candidate == line), "{line} in\n{info}");
        }
    }

    #[test]
    fn the_mtree_lists_directories_and_files_with_their_digests() {
        let tree = mtree(&files(), 0);
        let lines = tree.lines().collect::<Vec<_>>();
        assert_eq!(lines[0], "#mtree");
        assert!(lines.contains(&"./usr time=0.0 mode=755 type=dir"));
        assert!(lines.contains(&"./usr/bin time=0.0 mode=755 type=dir"));
        let binary = format!(
            "./usr/bin/notes time=0.0 mode=755 size=4 sha256digest={}",
            crate::package::zip::hash_of(b"\x7fELF")
        );
        assert!(lines.contains(&binary.as_str()), "{tree}");
    }

    #[test]
    fn the_metadata_comes_first_in_the_archive_and_the_package_is_reproducible() {
        let archive = package(&metadata(), &files(), 0);
        assert_eq!(&archive[..7], b".MTREE\0");
        let text = String::from_utf8_lossy(&archive);
        let info = text.find(".PKGINFO\0").expect(".PKGINFO");
        assert!(info < text.find("usr/\0").expect("the files"), "before the files");
        assert_eq!(archive, package(&metadata(), &files(), 0));
    }

    /// Where `pacman` is installed, it reads the package back: its
    /// metadata and its file list.
    #[test]
    fn pacman_itself_reads_the_package() {
        let Some(tool) = super::super::which("pacman") else {
            eprintln!("skipped: pacman is not installed");
            return;
        };
        let directory =
            std::env::temp_dir().join(format!("rustnative-pacman-{}", std::process::id()));
        std::fs::create_dir_all(&directory).expect("a temporary directory");
        let path = directory.join("notes-1.2.3-1-x86_64.pkg.tar");
        std::fs::write(&path, package(&metadata(), &files(), 0)).expect("written");
        let run = |args: &[&str]| {
            let output =
                std::process::Command::new(&tool).args(args).arg(&path).output().expect("runs");
            let text = String::from_utf8_lossy(&output.stdout).into_owned()
                + &String::from_utf8_lossy(&output.stderr);
            assert!(output.status.success(), "pacman {args:?}: {text}");
            text
        };
        let info = run(&["-Qip"]);
        for expected in ["notes", "1.2.3-1", "x86_64", "gtk4>=4.14", "libsoup3"] {
            assert!(info.contains(expected), "{expected} in\n{info}");
        }
        let list = run(&["-Qlp"]);
        assert!(list.contains("notes /usr/bin/notes"), "{list}");
        assert!(!list.contains(".PKGINFO") && !list.contains(".MTREE"), "{list}");
        let _ = std::fs::remove_dir_all(&directory);
    }
}
