[package]
name = "rustnative-web-macros"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Rust Native's web macros: #[client] (client logic compiled to JavaScript) and #[server]"
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["web", "macro", "javascript", "native", "framework"]
categories = ["development-tools::procedural-macro-helpers", "web-programming"]

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
rustnative-webgen.workspace = true
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }